project:
  type: website
  output-dir: docs

website:
  title: "biobyte"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dagsdags212

resources:
  - "assets/*"

format:
  bookup-html+light:
    toc: true
    toc-depth: 3
    embed-fonts: true

